### PR TITLE
Allow routing to wildcard subdomains

### LINKED ISSUE #30: Wild card domains
Has anyone had any luck with wildcard domains?

### PR DESCRIPTION
**Pull request by kevinmcconnell**
This allows routing to wildcard subdomains by specifying a target like:

    --target=*.example.com

This matches requests to hosts with any subdomain in place of the `*`. It does *not* match multiple levels of subdomain to a single `*`, nor are multiple `*` allowed in a single host. Rather it behaves much like the wildcard matching in TLS certificates does.

Automatic TLS is not currently supported with wildcard hosts (because the challenge types we use -- `http-01` and `tls-alpn-01` -- can't be used to generate wildcard certificates). However you can bring your own wildcard certificates using `--tls-certificate-path` / `--tls-private-key-path`.

cc @djmb 

Closes #30

### CODE REVIEW

**Comment by dmarczal** [comment]
Hello, How to use this options --tls-certificate-path / --tls-private-key-path with kamal 2?

**Comment by kevinmcconnell** [comment]
@dmarczal unfortunately these options aren't available in Kamal 2 yet, but we're hoping to get them into the next release.

Once that ships you'll be able to specify the certificate details in the deployment configuration.

**Comment by dmarczal** [comment]
@kevinmcconnell Thank you for your response! It would be great if this feature comes with the next release.

I set it up manually, and it works perfectly.

**Comment by webmix** [comment]
> @kevinmcconnell Thank you for your response! It would be great if this feature comes with the next release.
> 
> I set it up manually, and it works perfectly.

Hi @dmarczal 
May I ask you how do you set it up manually ?

I currently got my certificates issued, but I have no idea how to tell the server to use them

**Comment by MarczalTSIGP** [comment]
> > @kevinmcconnell Thank you for your response! It would be great if this feature comes with the next release.
> > I set it up manually, and it works perfectly.
> 
> Hi @dmarczal May I ask you how do you set it up manually ?
> 
> I currently got my certificates issued, but I have no idea how to tell the server to use them

Hi, for sure.

I still need to create an automatic script for this (kamal hook) to run after deploy. But I follow these steps:

1. Login at the server by SSH

2. Get the certificates, (for example, using let's encrypt)
```certbot certonly --dns-digitalocean --dns-digitalocean-credentials ~/certbot-creds.ini -d '*.domain.com'```

3. Copy the certificates to the kamal-proxy container
```docker cp /etc/letsencrypt/archive/domain.com kamal-proxy:/home/kamal-proxy```

4. Enter at kamal-proxy container
```docker exec -it kamal-proxy bash```

5. Run `kamal-proxy list` to see the target ID`

6. Deploy the subdomain
```kamal-proxy deploy subdomain-DOMAIN-web --target TARGET_ID:80 --host *.domain.com --tls --tls-certificate-path /home/kamal-proxy/domain.com/cert1.pem --tls-private-key-path /home/kamal-proxy/privkey1.pem```

You may have permission issues with the certificates keys. If it happens, simply change the owner the folder that contains the certificates `chown kamal-proxy:kamal-proxy  domain.com`. 

I hope this helps.

**Comment by dmarczal** [comment]
> > @kevinmcconnell Thank you for your response! It would be great if this feature comes with the next release.
> > I set it up manually, and it works perfectly.
> 
> Hi @dmarczal May I ask you how do you set it up manually ?
> 
> I currently got my certificates issued, but I have no idea how to tell the server to use them

Hi, for sure.

I still need to create an automatic script for this (kamal hook) to run after deploy. But I follow these steps:

1. Login at the server by SSH

2. Get the certificates, (for example, using let's encrypt)
```
certbot certonly --dns-digitalocean --dns-digitalocean-credentials ~/certbot-creds.ini -d '*.domain.com'
```

3. Copy the certificates to the kamal-proxy container
```
docker cp /etc/letsencrypt/archive/domain.com kamal-proxy:/home/kamal-proxy
```

4. Enter at kamal-proxy container
```
docker exec -it kamal-proxy bash
```

5. Run `kamal-proxy list` to see the target ID`

6. Deploy the subdomain
```
kamal-proxy deploy subdomain-DOMAIN-web --target TARGET_ID:80 --host *.domain.com --tls --tls-certificate-path /home/kamal-proxy/domain.com/cert1.pem --tls-private-key-path /home/kamal-proxy/privkey1.pem
```

You may have permission issues with the certificates keys. If it happens, simply change the owner the folder that contains the certificates `chown kamal-proxy:kamal-proxy  domain.com`. 

I hope this helps.

**Pull request merged**
